name: CI

on:
  push:
    branches: [ "development","staging" ]
    tags: [ "v*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: view data
        run: cat myFeature_a.txt

      # - name: list all files
      #   run: ls -ltrh

      # - name: Run a one-line script
      #   run: echo Hello, world!

      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
